linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
      # - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
      #- gocyclo
    - godot
      #- goerr113
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
      #- testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # come back to this.  might be useful later.
  # - prealloc
  # - wsl
  #
  # probably not worrying about this.
  # - godox
