on: [push, pull_request]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Install libpcap
        run: sudo apt-get install libpcap-dev
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
            version: v1.54.0
