on: [push, pull_request]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install libpcap
        run: sudo apt-get install libpcap-dev
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
            version: v1.41.1
